apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  GITHUB_WEBHOOK_SECRET: "myWebhookSecret_abc123XYZ789"
  GITHUB_APP_ID: "3441502"
  GITHUB_APP_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA0S2c1RNHyOCmBC8IlwcyeantlmGR46LQOFCtplB3DLI9tsMg
    zEKCNo+G8p/oZymI5PHy/xHJzIXX/2reTfjnEMMGtm/fp+oh6l435gm4kGJEcYUO
    Ke6nyqmCa6fh7Zf0PCdTXYzBeSYVgyCjUDqJbRHQHWk+MCfkyxAAWDedvAuKLncd
    qMbpVAZehiAS3030k9XA7PLgtNkonkUJKzh7BiDqw+d+a0/Q5ygxlQygKyZWnyT6
    xv/gI5FUzOC8upkRR18ImDg3eZ5mBZfDeiUEprsmXiNJiGXoTbGtdnWgjJ1VQ4Ch
    hRqiuVwWDwjqiX1/INJ8NCfKpAWChJlzmyyURQIDAQABAoIBAHTZqByXUqhyZgs8
    Qu4rRRUVyfURuC+TigGLgBXCKV7cSwFHa5DvLlJQRzBOB8NpPmG2junSBArOUeUK
    y/h+rIV+jMdpI2Vns157F3rXv1RYsKdBjrH58Z2Sp5qABAN3uSXJShaeRI3qqmW/
    27s7l/1nz/w+CFFaV8Lfw3GEUAb04MFViBX0bK03nhXizm9cvFTDg2PZgwg5J/XK
    4RurHlmmoDVJUnv8XYCXAH6FZ1w9x8xRymnVgIdJMnIp8desRVZ+EjT4YNLjjKL7
    DY5uqItHDC19SoNQc5q8WjpkU0DuGf4bgBjAu2ik33NdYjCaBOlj8kpcZNRAcoR0
    lZi66UECgYEA6q+4K0F519YPBnTiQLQ3sXuCnUc1OxiOZl8q60U33UZPBlz1ccqn
    4dlPwDYj5RYFuXr7upH6HmHD21GsN6mFbO5jrYT78wEa+2MZ7uiSGDcyy3HhOaV9
    7SbfHp9pqJYsbD2B/64r/XzU2RRkeIwKefOvyvl4MLHS4OOiH5/p8nkCgYEA5CzY
    pFA/8hyVt8WaX4Qb31BSonvuvjLMytc93utF9HdpU1Hb6Ysc3jkgVVyTBBoctjAp
    0a8vKibDmlK3EnI+1dmbu9Tw5wMwP+Rg0jkEj5aKVLWtZhnnRn7xoF9QrjzVVPXK
    D2mIpl+krS5ansju56vrd374nCpMNHtIO3vvXS0CgYAB6nNPbxZmi6nNvLCIJLB7
    s21qiUVG+TlYXpiEGSmOld9ZRvL9/dCHCHYdNJPwb9CWJgneCQkIrHWj2bPVNH4R
    WJTZuscvwaeNu85fY+ilZ/XzMTfMd6xifjm+D0EWjjtImuvvwWU8iYNXTlJPpZ0E
    R9f8iTLQ+vKkwVb2eSC4yQKBgB+/ublLTUqD/bUfcrZ9rF8rTwQ62GJwsRw8TOia
    thYpE2e7iSz65V5qdnxKME6uz3XuR7Nce+SSlj7/6WdQrDuXVtsQ6yBJyknpnitC
    McdE/CSDTwhY7Fxbx4U4HgLQhiKXPLFeTtxPjJtoSsWzUcK8ojvzV+Zq4EWhLdDR
    EuJVAoGBAKH45Jj7lvnCRF537acDrdVUNrJ8vvRDbC2zH2DIVgeohKy09jFA5hn1
    om9VNUFYJWwonP847NADraIv2GPt/eR2OM7m5oKyjOaiIEX9flaUd/HGnG5NBTW0
    a/+ZxXeTMHgYEYaAgNDIBvKeResQ2TCRNonvjR3mw1v71MshnqRy
    -----END RSA PRIVATE KEY-----
  OPENAI_API_KEY: "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"
  LANGFUSE_PUBLIC_KEY: "pk-lf-2eb4a82b-dd19-4102-bcea-4c567a5d73cd"
  LANGFUSE_SECRET_KEY: "sk-lf-0835e31b-7fcd-4c05-8639-1cd9a82ae2a0"
  DATABASE_URL: "postgresql+asyncpg://dbadmin:YourStrongPassword123!@ai-code-reviewer-postgres.cshe84og0h2z.us-east-1.rds.amazonaws.com/codereviewer"
